### PR TITLE
fix infinite compression if output file is inside the input folder

### LINKED ISSUE #287: Infinite archive compression if output file is inside of the input folder
### Version

385a630d0ecf81344d91266d6552030387bdca0d (main branch)

### Description

When compressing an archive like `.tar`, if the output file is inside of the input folder, Ouch enters an infinite compression state.

That's because the output is being considered as the output, so any written bytes are read again, and again, and that's an infinite loop.

### Current Behavior

$ ouch compress . archive.tar

Runs forever and will slowly exhaust all your hard drive space.

Example compressing a 2 GB folder:
image

### Expected Behavior

Ouch should ignore the output as the input file, like `tar` util does.

```
$ tar -cvf archive.tar .
...
...
tar: ./out.tar: file is the archive; not dumped
```

### Additional Information

There is a check for skipping input files that are the same as the output file at https://github.com/ouch-org/ouch/blob/385a630d0ecf81344d91266d6552030387bdca0d/src/commands/mod.rs#L406-L419.

But in this case it's necessary to check while iterating in folder structures.

### LINKED ISSUE #292: Output of info logs is duplicated
### Version

bda6c270629711cd9072826471553c58766daf56 (main branch)

### Description

When trying to decompress an archive, the text output of each line is duplicated.

### Current Behavior

```
$ ouch d nvidia-utils-515.65.01-2-x86_64.pkg.tar.zst -d nvidia-utils                                                                                    
[INFO] directory nvidia-utils created.directory nvidia-utils created.
[INFO] Created temporary directory /home/marcospb19/test/nvidia-utils/.tmphZhxno to hold decompressed elements.Created temporary directory /home/marcospb19/test/nvidia-utils/.tmphZhxno to hold decompressed elements.
[INFO] Successfully moved /home/marcospb19/test/nvidia-utils/.tmphZhxno to nvidia-utils/nvidia-utils-515.65.01-2-x86_64.pkg.Successfully moved /home/marcospb19/test/nvidia-utils/.tmphZhxno to nvidia-utils/nvidia-utils-515.65.01-2-x86_64.pkg.
[INFO] Successfully decompressed archive in nvidia-utils.Successfully decompressed archive in nvidia-utils.
[INFO] Files unpacked: 219Files unpacked: 219
```

### Expected Behavior

```
$ ouch d nvidia-utils-515.65.01-2-x86_64.pkg.tar.zst -d nvidia-utils                                                                                    
[INFO] directory nvidia-utils created.
[INFO] Created temporary directory /home/marcospb19/test/nvidia-utils/.tmphZhxno to hold decompressed elements.
[INFO] Successfully moved /home/marcospb19/test/nvidia-utils/.tmphZhxno to nvidia-utils/nvidia-utils-515.65.01-2-x86_64.pkg.
[INFO] Successfully decompressed archive in nvidia-utils.
[INFO] Files unpacked: 219
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by figsoda**
fixes #287 
fixes #292

moved the deduplication to when we are building the archive instead of before, so we don't have to iterate over the files, but that also means the progress bar is on, which makes it a little harder to print out the warning

using `same-file` crate since it is already used in `ignore` and deals with relative paths

### CODE REVIEW

File: src/progress.rs [hunk 1]
```diff
@@ -34,7 +39,13 @@ impl OutputLine for Stderr {
     }
 
     fn output_line_info(&mut self, args: Arguments) {
-        write!(self, "{}[INFO]{} {args}", *YELLOW, *RESET).unwrap();
+        write!(self, "{}[INFO]{} ", *YELLOW, *RESET).unwrap();
```
Comment (figsoda) [inline src/progress.rs:42]: this should fix #292 as well

**Review by marcospb19 — CHANGES_REQUESTED** [review]
lgtm!

**Review by marcospb19 — APPROVED** [review]
oops, lgtm!
