### PR TITLE
Fix decompression overwritting files without asking and failing on directories

### LINKED ISSUE #136: Decompression error when folder already exists at the place of output file
image

Ouch doens't really know that there is a folder there, it just gives this error message.

When it's not a folder, but a simple text file, it does ask if should overwrite.

### PR DESCRIPTION
**Pull request by SpyrosRoum**
Closes #136

### CODE REVIEW

File: src/commands.rs [hunk 1]
```diff
@@ -326,8 +326,22 @@ fn decompress_file(
...
+                            // ToDo: Maybe we should emphasise that `output_path` is a directory and everything inside it will be gone?
+                            fs::remove_dir_all(&output_path)?;
+                        }
+                        fs::File::create(&output_path)?
+                    } else {
+                        return Ok(());
+                    }
+                }
+                Err(e) => return Err(Error::from(e)),
+            };
```
Comment (marcospb19) [inline src/commands.rs:344]: Maybe if you move this to utils.rs, you can reuse the same code for the .zip and .tar parts?

Would that be possible? something like `create_file_checking_overwrites()` which receives one AsRef<Path> and tries to open with those OpenOptions configs you used, and returns `Result<Option<File>>`, with `Ok(None)` in case the used does not want to overwrite.

**Review by marcospb19 — CHANGES_REQUESTED** [review]

File: src/commands.rs (hunk 1 above)
Comment (SpyrosRoum) [reply src/commands.rs:344]: Yeah that's a good point

Comment (SpyrosRoum) [reply src/commands.rs]: I don't think this is really doable after all because the archives don't want the file to exist there at all. Good news is I caught a bug because of this.
I did extract the function anyway because I think it's a bit cleaner but I didn't end up using it in .zip and .tar
It *could* be used if I were to add some flags determining if the file should be created or not but I don't think it's worth it, what do you think?

Comment (marcospb19) [reply src/commands.rs]: I don't think that's worth too, but by how that function looked, I think it's better now on utils.rs :D .

**Review by marcospb19 — APPROVED** [review]

**Comment by marcospb19** [comment]
Awesome that you got another bug in this, makes me wonder how many specific errors like this still exist in `ouch`...

**Comment by SpyrosRoum** [comment]
With this out of the way I am thinking it might be time for a new release?
We have fixed many bugs, some of them pretty critical..

**Comment by marcospb19** [comment]
> With this out of the way I am thinking it might be time for a new release?

Yeah, it's been a long time since I said I was going to make a new release, we had too many changes.

I'm not sure what to put in the changelog, I think I'll make it more organized after the 1.0 release.

**Comment by SpyrosRoum** [comment]
> I'm not sure what to put in the changelog, I think I'll make it more organized after the 1.0 release.

I haven't used it personally but take a look at [realease-please](https://github.com/googleapis/release-please), it looks perfect for that kind of thing

**Comment by marcospb19** [comment]
I think it will get easier when ouch leaves the unstable stage, let's see, I'm not a huge fan of pushing extra requirements like the "conventionalcommits" because I prefer to keep it simple for people to contribute.
