### PR TITLE
Fix size unit inconsistency

### LINKED ISSUE #469: Progress size unit is inconsistent
### Version

0.4.1

### Description

The following is sculpted from decompression console log.

MB and MiB is mixed.

```
[INFO] ".tmpFVZWxh/OBS/2021-12-24 20-54-05.mp4" extracted. (617.30MiB)
[INFO] ".tmpFVZWxh/OBS/2021-12-24 19-53-20.mp4" extracted. (621.67MiB)
[INFO] ".tmpFVZWxh/OBS/2022-01-07 20-54-27.mp4" extracted. (635.01MB)
[INFO] ".tmpFVZWxh/OBS/2022-01-07 19-53-27.mp4" extracted. (630.09MiB)
[INFO] ".tmpFVZWxh/OBS/2022-01-21 19-54-01.mp4" extracted. (616.31MiB)
[INFO] ".tmpFVZWxh/OBS/2022-01-21 20-52-45.mp4" extracted. (643.32MiB)
[INFO] ".tmpFVZWxh/OBS/2022-02-04 18-53-47.mp4" extracted. (519.68MiB)
[INFO] ".tmpFVZWxh/OBS/2022-02-04 19-53-34.mp4" extracted. (632.81MiB)
[INFO] ".tmpFVZWxh/OBS/2022-02-18 19-53-25.mp4" extracted. (515.16MiB)
[INFO] ".tmpFVZWxh/OBS/2022-02-18 17-22-44.mp4" extracted. (540.20MiB)
[INFO] ".tmpFVZWxh/OBS/2022-02-18 18-53-49.mp4" extracted. (620.21MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-11 17-28-49.mp4" extracted. (535.01MB)
[INFO] ".tmpFVZWxh/OBS/2022-03-11 19-52-43.mp4" extracted. (539.44MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-11 18-53-08.mp4" extracted. (644.84MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-11 18-29-09.mp4" extracted. (22.77MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-18 16-31-23.mp4" extracted. (53.40MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-18 16-19-56.mp4" extracted. (70.79MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-18 16-23-10.mp4" extracted. (79.09MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-18 16-26-43.mp4" extracted. (98.95MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-18 16-14-20.mp4" extracted. (123.33MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-25 16-52-20.mp4" extracted. (439.51MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-25 16-19-09.mp4" extracted. (496.33MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-25 18-52-07.mp4" extracted. (665.34MiB)
[INFO] ".tmpFVZWxh/OBS/2022-03-18 18-03-46.mp4" extracted. (867.00MB)
[INFO] ".tmpFVZWxh/OBS/2022-03-18 18-43-09.mp4" extracted. (843.60MiB)
```

### Current Behavior

MB and MiB is mixed.

### Expected Behavior

All MiB or MB.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by marcospb19**
Fixes #469.

The problem was introduced by the crate `ubyte`, which was added in https://github.com/ouch-org/ouch/pull/333, reason is explained at #469.

This PR reintroduces @vrmiguel's code at https://github.com/ouch-org/ouch/commit/368a776b70ae9008fde5d26d09186469dd8c4768, but fixed for `GiB` instead of `GB`.

The code is a bit arcane with one magical constant and sizes are an approximation, but a good enough one for all real user purposes I can think of.

The `humansize` crate is too slow for us, even with the `no_alloc` feature enabled, so I came full-circle to our original implementation instead.

### CODE REVIEW

File: src/utils/formatting.rs [hunk 1]
```diff
@@ -86,3 +86,81 @@ pub fn nice_directory_display(path: &Path) -> Cow<str> {
...
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        let &Self(num) = self;
+
+        debug_assert!(num >= 0.0);
+        if num < 1_f64 {
+            return write!(f, "{} B", num);
+        }
+
+        let delimiter = 1000_f64;
+        let exponent = cmp::min((num.ln() / 6.90775).floor() as i32, 4);
```
Comment (marcospb19) [inline src/utils/formatting.rs:112]: The constant `6.90775` here is arcane-event-horizon-magic, but it works.

If someone wants to refactor and it ends up as fast as it is, that's great, but I'm not the one who's gonna touch this relic.

I actually wanted MB instead of MiB, but I don't know how to the change the code to do so xD.
